package com.nbro.service;

import com.nbro.Exceptions.ErrorMessages;
import com.nbro.domain.dto.ReleaseRequestDTO;
import com.nbro.domain.entity.Release;
import com.nbro.repository.ReleaseRepository;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

/**
 * Handles all business logic related to releases.
 * This is the middle layer between the controller (which receives requests)
 * and the database (which stores data).
 * <p>
 * All validation, rules, and decisions about releases live here.
 * The controller just passes data in and gets results back.
 */
@Service
@RequiredArgsConstructor
public class ReleaseService {

    private static final Logger logger = LoggerFactory.getLogger(ReleaseService.class);

    /**
     * Used to read and write release records in the database
     */
    private final ReleaseRepository releaseRepository;

    /**
     * Creates a new release request in the system.
     * <p>
     * Validation order:
     * 1. Jira key must follow the format PROJECT-123 e.g. RM-1, SCRUM-5
     * 2. Jira key must not already exist in the database
     * 3. Title must not be empty
     * <p>
     * If all validations pass, the release is saved with status DRAFT by default.
     *
     * @param request - all the details of the release submitted by the user
     * @return the saved Release object with its generated ID
     * @throws IllegalArgumentException if any validation fails
     */
    public Release createRelease(ReleaseRequestDTO request) {

        // Validate Jira key format — must be letters, dash, then numbers e.g. RM-1
        if (!request.getJiraKey().toUpperCase().matches("^[A-Z]+-[0-9]+$")) {
            throw new IllegalArgumentException(ErrorMessages.INVALID_JIRA_KEY_FORMAT);
        }

        // Check if a release with this Jira key already exists
        // We don't want duplicate releases for the same Jira issue
        if (releaseRepository.findByJiraKeyIgnoreCase(request.getJiraKey()).isPresent()) {
            throw new IllegalArgumentException(String.format(ErrorMessages.DUPLICATE_JIRA_KEY, request.getJiraKey()));
        }

        // Title is required — every release must have a meaningful name
        if (request.getTitle() == null || request.getTitle().trim().isEmpty()) {
            throw new IllegalArgumentException(ErrorMessages.DETAILS_NOT_VALID);
        }

        // Build the Release object from the request data
        // Status defaults to DRAFT automatically (set in the entity)
        // ID, createdAt, and updatedAt are auto generated by JPA
        Release release = Release.builder()
                .jiraKey(request.getJiraKey().toUpperCase())
                .title(request.getTitle())
                .postReleaseNotes(request.getPostReleaseNotes())
                .deployerId(request.getDeployerId())
                .releaseManagerId(request.getReleaseManagerId())
                .rollBackPlan(request.getRollBackPlan())
                .preReleaseChecklist(request.getPreReleaseChecklist())
                .deploymentSteps(request.getDeploymentSteps())
                .servicesImpacted(request.getServicesImpacted())
                .targetEnvironment(request.getTargetEnvironment())
                .releaseType(request.getReleaseType())
                .build();

        logger.info("Release created successfully with Jira key: {}", release.getJiraKey());
        return releaseRepository.save(release);
    }

    /**
     * Returns all releases in the system.
     * Used by the dashboard to show the full list of release requests.
     *
     * @return list of all releases, empty list if none exist
     */
    public List<Release> getAllReleases() {
        return releaseRepository.findAll();
    }

    /**
     * Returns a single release by its unique ID.
     * Used when a user clicks on a specific release to view its details.
     *
     * @param releaseId - the UUID of the release to fetch
     * @return the Release object if found
     * @throws RuntimeException if no release exists with the given ID
     */
    public Release getReleaseById(UUID releaseId) {
        return releaseRepository.findById(releaseId)
                .orElseThrow(() -> new RuntimeException("Release Not Found"));
    }
}